# Generated by Django 5.1.4 on 2024-12-13 18:14

from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('concierto', 'Concierto'), ('conferencia', 'Conferencia'), ('feria', 'Feria'), ('congreso', 'Congreso'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
